An error occurred while executing the following cell:
------------------
# Imports
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import jax
import jax.numpy as jnp
import numpy as np

try:
    import sklearn.datasets
except ModuleNotFoundError:
    %pip install -qq -U scikit-learn
    import sklearn.datasets

try:
    import flax
    import flax.linen as nn
    from flax.training import train_state
except ModuleNotFoundError:
    %pip install -qq -U flax
    import flax
    import flax.linen as nn
    from flax.training import train_state

try:
    import optax
except ModuleNotFoundError:
    %pip install -qq -U optax
    import optax

try:
    import edward2.jax as ed
except ModuleNotFoundError:
    %pip install -qq -U "git+https://github.com/google/edward2.git#egg=edward2"
    import edward2.jax as ed
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4374/608523586.py in <module>
     31 try:
---> 32     import edward2.jax as ed
     33 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'edward2'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/tmp/ipykernel_4374/608523586.py in <module>
     33 except ModuleNotFoundError:
     34     get_ipython().run_line_magic('pip', 'install -qq -U "git+https://github.com/google/edward2.git#egg=edward2"')
---> 35     import edward2.jax as ed

~/miniconda3/envs/py37/lib/python3.7/site-packages/edward2/__init__.py in <module>
     41 
     42 try:
---> 43   from edward2 import tensorflow
     44   from edward2.tensorflow import *  # pylint: disable=wildcard-import
     45   # By default, `import edward2 as ed` uses the TensorFlow backend's namespace.

~/miniconda3/envs/py37/lib/python3.7/site-packages/edward2/tensorflow/__init__.py in <module>
     16 """Edward2 probabilistic programming language with TensorFlow backend."""
     17 
---> 18 from edward2.tensorflow import constraints
     19 from edward2.tensorflow import generated_random_variables
     20 from edward2.tensorflow import initializers

~/miniconda3/envs/py37/lib/python3.7/site-packages/edward2/tensorflow/constraints.py in <module>
     25 """
     26 
---> 27 import tensorflow as tf
     28 
     29 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/__init__.py in <module>
     35 import typing as _typing
     36 
---> 37 from tensorflow.python.tools import module_util as _module_util
     38 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     39 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/__init__.py in <module>
     34 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     35 
---> 36 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
     37 from tensorflow.python.eager import context
     38 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     24 
     25 # Perform pre-load sanity checks in order to produce a more actionable error.
---> 26 self_check.preload_check()
     27 
     28 # pylint: disable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/self_check.py in preload_check()
     63     cpu_feature_guard_library = os.path.join(
     64         os.path.dirname(__file__), "../../core/platform/_cpu_feature_guard.so")
---> 65     ctypes.CDLL(cpu_feature_guard_library)

~/miniconda3/envs/py37/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/../../core/platform/_cpu_feature_guard.so: cannot open shared object file: No such file or directory
OSError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/../../core/platform/_cpu_feature_guard.so: cannot open shared object file: No such file or directory
