An error occurred while executing the following cell:
------------------
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
    IS_COLAB = True
except Exception:
    IS_COLAB = False

# TensorFlow â‰¥2.0 is required
try:
    import tensorflow as tf
except ModuleNotFoundError:
    %pip install -qq tensorflow
    import tensorflow as tf
from tensorflow import keras

assert tf.__version__ >= "2.0"

if not tf.config.list_physical_devices("GPU"):
    print("No GPU was detected. DNNs can be very slow without a GPU.")
    if IS_COLAB:
        print("Go to Runtime > Change runtime and select a GPU hardware accelerator.")
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_2985/1663250572.py in <module>
      9 try:
---> 10     import tensorflow as tf
     11 except ModuleNotFoundError:

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/__init__.py in <module>
     36 
---> 37 from tensorflow.python.tools import module_util as _module_util
     38 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader

ModuleNotFoundError: No module named 'tensorflow.python.tools'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_2985/1663250572.py in <module>
     11 except ModuleNotFoundError:
     12     get_ipython().run_line_magic('pip', 'install -qq tensorflow')
---> 13     import tensorflow as tf
     14 from tensorflow import keras
     15 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/__init__.py in <module>
     43 _tf2.enable()
     44 
---> 45 from ._api.v2 import __internal__
     46 from ._api.v2 import __operators__
     47 from ._api.v2 import audio

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/_api/v2/__internal__/__init__.py in <module>
      6 import sys as _sys
      7 
----> 8 from . import autograph
      9 from . import decorator
     10 from . import dispatch

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py in <module>
      6 import sys as _sys
      7 
----> 8 from tensorflow.python.autograph.core.ag_ctx import control_status_ctx
      9 from tensorflow.python.autograph.impl.api import tf_convert

ModuleNotFoundError: No module named 'tensorflow.python.autograph'
ModuleNotFoundError: No module named 'tensorflow.python.autograph'
