An error occurred while executing the following cell:
------------------
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

try:
    import torch
except ModuleNotFoundError:
    %pip install -qq torch
    import torch

try:
    from torchvision.utils import make_grid
except ModuleNotFoundError:
    %pip install -qq torchvision
    from torchvision.utils import make_grid

import torch.nn as nn
from torchvision.datasets import MNIST
import torch.nn.functional as F
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

try:
    from pytorch_lightning import LightningModule, Trainer
except ModuleNotFoundError:
    %pip install -qq pytorch-lightning
    from pytorch_lightning import LightningModule, Trainer

try:
    from einops import rearrange
except ModuleNotFoundError:
    %pip install -qq einops
    from einops import rearrange

try:
    import probml_utils
except ModuleNotFoundError:
    %pip install -qq git+https://github.com/probml/probml-utils.git
    import probml_utils

from probml_utils import savefig

from probml_utils.lvm_plots_utils import (
    get_random_samples,
    get_grid_samples,
    plot_scatter_plot,
    get_imrange,
    plot_grid_plot,
    plot_scatter_plot,
)

import seaborn as sns
from torchvision.utils import make_grid
from probml_utils.vae_conv_mnist import ConvVAE

%pip install -qq test-tube umap
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_4703/3536696859.py in <module>
     41 from probml_utils import savefig
     42 
---> 43 from probml_utils.lvm_plots_utils import (
     44     get_random_samples,
     45     get_grid_samples,

~/miniconda3/envs/py37/lib/python3.7/site-packages/probml_utils/lvm_plots_utils.py in <module>
      1 import os
      2 
----> 3 import umap
      4 from typing import Callable, Tuple
      5 

~/miniconda3/envs/py37/lib/python3.7/site-packages/umap/__init__.py in <module>
      5     with catch_warnings():
      6         simplefilter("ignore")
----> 7         from .parametric_umap import ParametricUMAP
      8 except ImportError:
      9     warn(

~/miniconda3/envs/py37/lib/python3.7/site-packages/umap/parametric_umap.py in <module>
     26     raise ImportError("umap.parametric_umap requires Tensorflow >= 2.0") from None
     27 
---> 28 TF_MAJOR_VERSION = int(tf.__version__.split(".")[0])
     29 if TF_MAJOR_VERSION < 2:
     30     warn(

AttributeError: module 'tensorflow' has no attribute '__version__'
AttributeError: module 'tensorflow' has no attribute '__version__'
