An error occurred while executing the following cell:
------------------
import os
from functools import partial

try:
    import torch
except ModuleNotFoundError:
    %pip install -qq torch
    import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

try:
    import pyro
except ModuleNotFoundError:
    %pip install -qq pyro
    import pyro
import pyro.distributions as dist
from pyro.nn import PyroSample
from pyro.infer.autoguide import AutoDiagonalNormal
from pyro.infer import Predictive
from pyro.infer import SVI, Trace_ELBO
from pyro.infer import MCMC, NUTS

pyro.set_rng_seed(1)

from torch import nn
from pyro.nn import PyroModule
------------------

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_4174/1419653647.py in <module>
      3 
      4 try:
----> 5     import torch
      6 except ModuleNotFoundError:
      7     get_ipython().run_line_magic('pip', 'install -qq torch')

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/__init__.py in <module>
    200     if USE_GLOBAL_DEPS:
    201         _load_global_deps()
--> 202     from torch._C import *  # noqa: F403
    203 
    204 # Appease the type checker; ordinarily this binding is inserted by the

ImportError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
ImportError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
